name: bitshare
options:
  bundleIdPrefix: share.bitshare
  deploymentTarget:
    iOS: 16.0
    macOS: 13.0
  createIntermediateGroups: true
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  
targets:
  bitshare_iOS:
    type: application
    platform: iOS
    sources: 
      - bitshare
    resources:
      - bitshare/Assets.xcassets
      - bitshare/LaunchScreen.storyboard
    info:
      path: bitshare/Info.plist
      properties:
        CFBundleDisplayName: bitshare
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSBluetoothAlwaysUsageDescription: bitshare uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: bitshare uses Bluetooth to discover and connect with other bitshare users for secure file transfers.
        UIBackgroundModes:
          - bluetooth-central
          - bluetooth-peripheral
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - bitshare
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: share.bitshare
      PRODUCT_NAME: bitshare
      INFOPLIST_FILE: bitshare/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: bitshare/bitshare.entitlements
    dependencies:
      - target: bitshareShareExtension
        embed: true
        
  bitshare_macOS:
    type: application
    platform: macOS
    sources: 
      - bitshare
    resources:
      - bitshare/Assets.xcassets
    info:
      path: bitshare/Info.plist
      properties:
        CFBundleDisplayName: bitshare
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSBluetoothAlwaysUsageDescription: bitshare uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: bitshare uses Bluetooth to discover and connect with other bitshare users for secure file transfers.
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - bitshare
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: share.bitshare
      PRODUCT_NAME: bitshare
      INFOPLIST_FILE: bitshare/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: bitshare/bitchat-macOS.entitlements
        
  bitshareShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - bitshareShareExtension
    info:
      path: bitshareShareExtension/Info.plist
      properties:
        CFBundleDisplayName: bitshare
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: share.bitshare.ShareExtension
      INFOPLIST_FILE: bitshareShareExtension/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      CODE_SIGN_ENTITLEMENTS: bitshareShareExtension/bitshareShareExtension.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES

  bitshareTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - bitshareTests
    dependencies:
      - target: bitshare_iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: share.bitshare.tests
      INFOPLIST_FILE: bitchatTests/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/bitchat.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/bitchat
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      
  bitshareTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources: 
      - bitshareTests
    dependencies:
      - target: bitshare_macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: share.bitshare.tests
      INFOPLIST_FILE: bitchatTests/Info.plist
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/bitchat.app/Contents/MacOS/bitchat
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y

schemes:
  bitshare (iOS):
    build:
      targets:
        bitshare_iOS: all
        bitshareShareExtension: all
    run:
      config: Debug
      executable: bitshare_iOS
    test:
      config: Debug
      targets:
        - bitshareTests_iOS
    profile:
      config: Release
      executable: bitshare_iOS
    analyze:
      config: Debug
    archive:
      config: Release
      
  bitshare (macOS):
    build:
      targets:
        bitshare_macOS: all
    run:
      config: Debug
      executable: bitshare_macOS
    test:
      config: Debug
      targets:
        - bitshareTests_macOS
    profile:
      config: Release
      executable: bitshare_macOS
    analyze:
      config: Debug
    archive:
      config: Release
